"""
JWT Authentication & Validation
Verifies JWT tokens generated by Spring Boot
"""
from fastapi import Depends, HTTPException, status
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from jose import JWTError, jwt
from typing import Dict
from .config import settings
import logging

logger = logging.getLogger(__name__)

# HTTP Bearer token extractor
security = HTTPBearer()


def verify_jwt_token(
    credentials: HTTPAuthorizationCredentials = Depends(security)
) -> Dict[str, str]:
    """
    Verify JWT token from Spring Boot
    
    This function:
    1. Extracts the Bearer token from Authorization header
    2. Decodes using the same JWT_SECRET as Spring Boot
    3. Validates the token structure and claims
    4. Returns user email and role
    
    Args:
        credentials: HTTPAuthorizationCredentials from FastAPI security
    
    Returns:
        Dict with 'email' and 'role' keys
    
    Raises:
        HTTPException: If token is invalid or expired
    """
    token = credentials.credentials
    
    try:
        # Decode JWT with same secret as Spring Boot
        payload = jwt.decode(
            token, 
            settings.JWT_SECRET, 
            algorithms=[settings.JWT_ALGORITHM]
        )
        
        # Extract claims (Spring Boot uses 'sub' for email)
        email: str = payload.get("sub")
        role: str = payload.get("role")
        
        # Validate required claims
        if email is None or role is None:
            logger.warning("JWT missing required claims: email or role")
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Invalid authentication credentials",
                headers={"WWW-Authenticate": "Bearer"},
            )
        
        logger.info(f"JWT validated for user: {email}, role: {role}")
        
        return {
            "email": email,
            "role": role,
            "user_id": payload.get("userId"),  # Optional claim
        }
    
    except JWTError as e:
        logger.error(f"JWT validation failed: {str(e)}")
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Could not validate credentials",
            headers={"WWW-Authenticate": "Bearer"},
        )
    except Exception as e:
        logger.error(f"Unexpected error during JWT validation: {str(e)}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Authentication error"
        )


def verify_role(required_roles: list[str]):
    """
    Dependency to verify user has required role
    
    Usage:
        @router.get("/admin-only")
        async def admin_endpoint(auth: dict = Depends(verify_jwt_token)):
            if auth["role"] not in ["ADMIN", "SUPER_ADMIN"]:
                raise HTTPException(403, "Insufficient permissions")
    
    Args:
        required_roles: List of acceptable roles
    
    Returns:
        Function that checks role from JWT
    """
    def role_checker(auth: Dict = Depends(verify_jwt_token)) -> Dict:
        if auth["role"] not in required_roles:
            logger.warning(
                f"Access denied: User {auth['email']} with role {auth['role']} "
                f"attempted to access endpoint requiring {required_roles}"
            )
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail=f"Insufficient permissions. Required roles: {required_roles}"
            )
        return auth
    
    return role_checker
